# Export an exact environment from a selected Python interpreter.
args <- commandArgs(trailingOnly = TRUE)
get_arg <- function(flag, default = "") {
  index <- match(flag, args)
  if (is.na(index) || index == length(args)) return(default)
  args[[index + 1L]]
}

python <- get_arg("--python", Sys.getenv("RETICULATE_PYTHON", unset = ""))
if (!nzchar(python)) {
  stop("Pass --python with the exact interpreter to export.", call. = FALSE)
}
python <- normalizePath(python, winslash = "/", mustWork = TRUE)
python_dir <- dirname(python)
prefix <- if (basename(python_dir) %in% c("bin", "Scripts")) dirname(python_dir) else python_dir
is_conda <- dir.exists(file.path(prefix, "conda-meta"))
default_output <- if (is_conda) {
  file.path("provenance", "python-environment.yml")
} else {
  file.path("provenance", "python-requirements.txt")
}
out <- get_arg("--output", default_output)
dir.create(dirname(out), recursive = TRUE, showWarnings = FALSE)

run_command <- function(command, arguments) {
  result <- system2(command, arguments, stdout = TRUE, stderr = TRUE)
  status <- attr(result, "status", exact = TRUE)
  if (!is.null(status) && status != 0L) {
    stop(paste(result, collapse = "\n"), call. = FALSE)
  }
  result
}
run_python <- function(arguments) run_command(python, arguments)

python_version <- run_python("--version")
pip_version <- run_python(c("-m", "pip", "--version"))
pip_check <- run_python(c("-m", "pip", "check"))
header <- c(
  "# Exact Python environment generated by scripts/export_python_lock.R",
  paste("# generated_utc:", format(Sys.time(), tz = "UTC", usetz = TRUE)),
  paste("# python:", python),
  paste("# python_version:", paste(python_version, collapse = " ")),
  paste("# pip_version:", paste(pip_version, collapse = " ")),
  paste("# pip_check:", paste(pip_check, collapse = " | "))
)

if (is_conda) {
  conda_arg <- get_arg("--conda", "")
  candidates <- c(
    conda_arg,
    file.path(prefix, "Scripts", "conda.exe"),
    file.path(dirname(prefix), "Scripts", "conda.exe"),
    file.path(dirname(dirname(prefix)), "Scripts", "conda.exe"),
    unname(Sys.which("conda"))
  )
  candidates <- unique(candidates[nzchar(candidates) & file.exists(candidates)])
  if (!length(candidates)) {
    stop("Conda environment detected but conda executable was not found; pass --conda.", call. = FALSE)
  }
  conda <- normalizePath(candidates[[1]], winslash = "/", mustWork = TRUE)
  exported <- run_command(conda, c("env", "export", "--prefix", shQuote(prefix)))
  exported <- exported[!grepl("^prefix:", exported)]
  name_index <- grep("^name:", exported)
  if (length(name_index)) exported[name_index[[1]]] <- paste("name:", basename(prefix))
  lines <- c(header, paste("# conda:", conda), exported)
} else {
  freeze <- run_python(c("-m", "pip", "freeze", "--all"))
  freeze <- sort(unique(freeze[nzchar(freeze)]))
  local_refs <- grepl(" @ file:", freeze, fixed = TRUE)
  if (any(local_refs)) {
    stop("pip freeze contains local file references and is not portable.", call. = FALSE)
  }
  lines <- c(header, freeze)
}

writeLines(lines, out, useBytes = TRUE)
message("Wrote Python environment: ", normalizePath(out, winslash = "/", mustWork = FALSE))
